name: Resonance Check

on:
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'

jobs:
  resonance-check:
    runs-on: ubuntu-latest

    steps:
    - name: 🌀 Checkout repository
      uses: actions/checkout@v3

    - name: 🧘 Run Resonance Reflection
      run: |
        echo "Running Resonance Check..."
        echo "Scanning for dissonance..."
        if grep -r -i 'exploit\|manipulate\|gamble' src/ docs/; then
          echo "::error::Potential ethical dissonance detected. Please review in light of TEP."
          exit 1
        else
          echo "✅ All clear. Your code hums with harmony."
        fi
